### ISSUE TITLE
Add Compatibility for influx cloud hosted service

### ISSUE THREAD

**Issue by umpvdr** [stackhero-io/node-red-contrib-stackhero-influxdb-v2#1]
I really like that this has been added as a node. If it could be altered to also add connectivity to Influx cloud hosted service I think it would benefit a lot of people

**Comment by Bacto** [comment]
Hi,

Could you give me more informations about what is required to make it compatible with InfluxDB Cloud?
I thought it will be working out of the box for remote services.

**Comment by umpvdr** [comment]
Hi,

Thanks for the reply, my mistake I was adding 'https://' to my URL when it is not needed. I can now connect to my Influx Cloud hosted DB. Thanks again

**Comment by Bacto** [comment]
Awesome :)
