### ISSUE TITLE
Unable to provide DB token from file

### ISSUE THREAD

**Issue by rpuskas0** [stackhero-io/node-red-contrib-stackhero-influxdb-v2#4]
Hi,

Would it be possible for you to modify the configuration node in a way, that would allow users to provide the DB token from a text file as well? This would most certainly be useful when using Node-Red from a Docker container, as this feature would allow people to use Docker Secrets for supplying tokens.

The implementation could very much look like what the default Node-Red MQTT config node has for providing certificates to allow connection encryption: if a checkbox is activated, the user is allowed to provide a file path in the text field, which in turn reads the sensitive data out from a text file.

Please consider adding this small feature, as it would truly be very useful. Thanks in advance.

**Comment by Bacto** [comment]
Hi @rpuskas0,
Unfortunately I don't see how to do it in a clean way.
With the node you can connect to multiple servers.
You have to set for each server the host, token, organization and bucket.
To do it properly we would have to pass and array of host/token/organization. That is I think too much work and you will have this kind of problems with other nodes.
Maybe it would be better to find a way to define credentials in Node-RED directly.
