### ISSUE TITLE
Support of strings with whitespaces

### ISSUE THREAD

**Issue by yenzor** [stackhero-io/node-red-contrib-stackhero-influxdb-v2#5]
Hi there,
thanks a lot for your node! Have you ever used a string including whitespaces for tags or measurement etc.?
I do not get it to work. According to Influx Line Protocol whitespaces, equal sign, comma... need to be escaped with a backslash in order to not mess up the command. But even if I put a backslash into the tag string that is put into the write node it does not work. According to the error message the backslash used for escaping is apparently removed at some point before the whole command string is given to InfluxDB, so in the end there is just the whitespace in the tag part of the command string, which is then interpreted by InfluxDB that the fieldKey already starts. 

Do you actively remove that backslash escape at some point when putting the tagKey string into the whole command string?

Example:
data: [
    {
      measurement: 'StringTest',

      tags: {
        deviceId: "Text\ withSpace"
      },

      fields: {
        test: 22
      },
    },
  ]

Best Regards,
Yenzor

**Comment by coalpower** [comment]
Same issue here. 
I can't add field value that includes space character.

It's allowed as per Line Protocol documentation
https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/#special-characters

**Comment by Bacto** [comment]
Problem solved with v1.0.4
Thanks for the issues :)
