### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by globaltopmedia** [stackhero-io/node-red-contrib-stackhero-influxdb-v2#7]
Trying to write to influxdb, but keep getting the TypeError: Cannot convert undefined or null to object 

My payload

{"data":{"gps_as_of":1605132723,"heading":53,"latitude":31.099831,"longitude":5.113069,"native_latitude":51.099831,"native_location_supported":1,"native_longitude":5.113069,"native_type":"wgs","power":0,"shift_state":"P","speed":null,"timestamp":1605132724637}}

Is the problem the speed? which is set to null?

**Comment by globaltopmedia** [comment]
formatting error at my end

**Comment by TheFreeman** [comment]
But same issue on my side.
I cannot figure out, why this is happening:

```js
18.2.2022, 13:27:13[node: Write to DB](http://192.168.0.10:1880/#)
msg : error

msg : Object
{
   "topic":"solar/logger/inverter/2",
   "payload":{
      "bucket":"solarinverter",
      "data":"HALLO"
   },
   "qos":0,
   "retain":false,
   "_msgid":"950145917887f192",
   "inverter":2
}
```

Any Idea?
